--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Alemiz112/StarGate-Atlantis
branches:
- master
- atlantis-netty
projects:
  StarGate-Atlantis:
    path: ""
    icon: "icon.png"
...
